### ISSUE TITLE
Toggling off the outline panel only makes the outline content hidden

### ISSUE THREAD

**Issue by pluma9** [cqroot/joplin-outline#25]
# Step to reproduce

- Open a note and outline panel
![before](https://user-images.githubusercontent.com/16544647/108080003-007ae900-70a2-11eb-9d53-e66c47b0a29b.png)
- Click the **Toggle Outline** button.

# Expectation

The outline content and the panel are hidden.

# Actual behavior

Only the content is hidden. Joplin still shows a blank panel.

![after](https://user-images.githubusercontent.com/16544647/108080477-7e3ef480-70a2-11eb-88ad-8edc4d794595.png)

# Environment

OS: Windows 10
Joplin version: 1.7.11
Joplin Outline plugin version: 1.1.3

**Comment by cqroot** [comment]
Yes, this is a known issue.

When the panel is on the far right, there will be a bug that only hides the content of the panel. It is recommended to put the outline panel on the left side of the note.

https://discourse.joplinapp.org/t/how-to-switch-the-display-and-hide-of-the-plugin-panel/13479

This problem may be fixed by joplin in the future.
