### ISSUE TITLE
No sidebar appears

### ISSUE THREAD

**Issue by Hoffenbar** [cqroot/joplin-outline#75]
In my joplin, the sidebar toc isn't visible. Do I have to configure something manually?
I'm using the portable version on Windows.
There is no `../Joplin/JoplinProfile/outline.css`, too, like mentioned in the configuration dialogue.

**Comment by cqroot** [comment]
I'm not sure what your problem is. You can check the following:

1. **Menu: Tools - Options - Plugins**. `outline` is installed and enabled.
2. **Menu: Tools - Plugins:Options**. Confirm whether the `outline` settings are displayed normally, as shown in the figure below.
   ![2023-01-30_15-27](https://user-images.githubusercontent.com/46901748/215413731-160e17d9-bd2f-41a5-b0cc-16d06673d346.png)
3. **Menu: Tools - Plugins:Options - Auto Hide**. If you have Auto Hide checked, the outline panel will not be displayed when your note has no title.

By default, the outline panel is displayed on the right side of the note, and the top title is `OUTLINE`.

`outline.css` is only used to modify the style of the panel, if it does not exist, the default style will be used and will not affect the display of the panel.

If this doesn't solve your problem, please give me more information.

**Comment by Hoffenbar** [comment]
The settings appear, but not the outline, wether _autohide_ is checked or not. Not toc appears on the right side of the document, event for documents with many headings. Yesterday I uninstalled and reinstalled the plugin, but this didn't helped either.

**Comment by cqroot** [comment]
I also don't know what the problem is. Never encountered before. Give me your system version, joplin version, plugin version, and some full screenshots.

**Comment by Hoffenbar** [comment]
Here is some screen shot from the layout function. Looks somewhat strange to me:

![image](https://user-images.githubusercontent.com/46227007/216692115-21e63ac8-f645-46de-a1e2-229448f2a9f8.png)

Maybe some interference with some other plugin....?

**Comment by Hoffenbar** [comment]
Ok, finally I've got it: I disabled the plugin _Favorits_; after that everything works as expected! I will file a ticket there...

**Comment by Hoffenbar** [comment]
But, another error remains: altering the layout only modifies it for the currently visible view. Switching the outline off and then on again restores the previous (wrong) layout:

![image](https://user-images.githubusercontent.com/46227007/216694105-d4800593-37ff-43f1-964c-8051cf586b45.png)

After Switching outline off:

![image](https://user-images.githubusercontent.com/46227007/216694180-0cf24cc0-e644-4fc7-ac9f-7b07a74f4325.png)

After switching outline ON again:

![image](https://user-images.githubusercontent.com/46227007/216694264-98166ae1-0f2f-47c0-a560-8e7331d1142c.png)

**Comment by Hoffenbar** [comment]
After some tests, I think this is a general layout manager thing w/Joplin. The possibilities there are somewhat strange, or I missed something yet. For now I will work with this layout:

![image](https://user-images.githubusercontent.com/46227007/216695231-53b128b1-2330-4c0a-8350-944a93dc2764.png)

which seems to stay as it should when switching on/off:

![image](https://user-images.githubusercontent.com/46227007/216695019-e5712397-453b-482c-a89e-9e394e80ef68.png)

![image](https://user-images.githubusercontent.com/46227007/216695160-65fb2499-f460-4372-a93c-e368264efb77.png)

**Comment by cqroot** [comment]
This is a known issue with joplin layout, not related to other plugins.

Joplin has not provided plugins with an api to modify the size yet, so I can't control the size.

As you did, it is recommended to put the outline panel in the middle rather than the far right.

**Comment by Hoffenbar** [comment]
Ok, then this issue is clarified, thank you very much!
